### PR TITLE
fix: error when use prettier v3

### LINKED ISSUE #164: Error output when using prettier v3
## Description

version 3 of prettier has been released.

- <https://prettier.io/blog/2023/07/05/3.0.0.html>

When using prettier ver3 with coc-prettier, an error seems to be output when starting the extension. It seems that coc-prettier needs to be adjusted for prettier ver3.

## Error

**Screen shot**:

coc-prettier-issue-use-prettier-v3

**CocInfo**:

```
...snip

2023-07-06T16:19:38.820 INFO (pid:2849) [services] - LanguageClient ESLint state change: stopped => starting
2023-07-06T16:19:38.822 ERROR (pid:2849) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'forEach')
      at PrettierEditService.getSelectors (/Users/yaegassy/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4439:18)
      at PrettierEditService.handleActiveTextEditorChanged (/Users/yaegassy/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4411:36)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: Cannot read properties of undefined (reading 'forEach')
    at PrettierEditService.getSelectors (/Users/yaegassy/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4439:18)
    at PrettierEditService.handleActiveTextEditorChanged (/Users/yaegassy/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4411:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

...snip
```

## Repro

```
mkdir -p $HOME/check-prettier3
cd $HOME/check-prettier3
npm init -y
npm i prettier@^3.0.0
nvim check.ts
```

### PR DESCRIPTION
**Pull request by weirongxu**
Fixes #164

### CODE REVIEW

**Comment by weirongxu** [comment]
https://github.com/neoclide/coc.nvim/discussions/4712

**Comment by geeogi** [comment]
plz merge

**Comment by minhchu** [comment]
While waiting for the merge, I patch the file directly `~/.config/coc/extensions/node_modules/coc-prettier/lib/index.js`:

Change:
```js
      const { languages: languages2 } = prettierInstance.getSupportInfo();
```
to:
```js
      const { languages: languages2 } = await Promise.resolve(prettierInstance.getSupportInfo());
```

**Comment by weirongxu** [comment]
@geeogi @minhchu The extension of support V3, I will be temporarily released to `:CocInstall @raidou/coc-prettier-v3`

**Comment by djanowski** [comment]
@neoclide Can you please merge this?

**Comment by stianjensen** [comment]
No updates on this repo since June last year. Are any @neoclide members still maintaining this repo, or should someone make a new maintained fork?

**Comment by sntx** [comment]
Hi @fannheyward . How do I replace coc-prettier by raidou/coc-prettier? Thank you!

**Pull request merged**
